### ISSUE TITLE
Data node with THREDDS + Nginx (unauthenticated)

### ISSUE THREAD

**Issue by mkjpryor-stfc** [ESGF/esgf-docker#112]
Data node deployment for Kubernetes and Ansible/Docker with THREDDS for OPeNDAP and Nginx for file-serving.

This will use vanilla THREDDS without custom filters.

At this stage, access is unauthenticated.

**Comment by nathanlcarlson** [comment]
Hi @mkjpryor-stfc , I was looking at this branch. A couple Q's. 

Would it be possible to use the official nginx image? 

Also, from what I can tell it appears that nginx will be serving SSL (via 8443). Would it be possible to perhaps assume something will be in front of it and that we shouldn't worry about SSL termination in the nginx server? I don't think it is guaranteed, but most Kubernetes users would have a preferred ingress, which likely uses LetsEncrypt to automatically manage certificates via something like traefik or caddy.

**Comment by mkjpryor-stfc** [comment]
@nathanlcarlson 

Our infrastructure guys aren't currently happy with us diverging from the CentOS platform that they know, hence why I'm not using the official Nginx or THREDDS images, both of which are based on Debian. I figured we as a community know CentOS better as well, so it probably won't harm. It's also quite nice to know exactly what is in your images.

The SSL settings you are referring to are for the default server block, which is used if no other server blocks match. It is important that this can respond to HTTPS. When running in Kubernetes, you are correct that the Nginx container will be behind an ingress controller which will handle the TLS termination for it. However in the Ansible-Docker installer, the same Nginx container will be the outward-facing proxy and so does need to respond correctly to HTTPS requests. There will be a separate server block to handle the actual hostname, but the default server must also respond correctly. Hope that makes sense.

**Comment by nathanlcarlson** [comment]
I have no reason to not trust the official nginx image, alpine or vanilla. It has likely been installed and used millions of times (it reports 1 billion plus downloads on docker hub). I also have no intention of ever interacting directing inside the container, so I don't really need to know what OS it is at all. I thought it was bad practice to do this type of thing anyway.

I see that it will (likely) be the edge server for simple Docker set ups. Would it be possible to just have a second config for that case? We could follow the pattern of mounting config volumes into the container at run-time so that the configuration is customizable, not built-in to the image.

**Comment by mkjpryor-stfc** [comment]
@nathanlcarlson 

I don't have a particular reason not to trust the official Nginx image either, but at the end of the day will still need to keep our infrastructure guys happy which for the time being means containers based on CentOS for us. In the longer term I would prefer to move to a lighter-weight distribution like Alpine, but our infrastructure team are nervous enough about the additional attack surface presented by containers that I would prefer not to push them. As such, I would prefer to stick with the CentOS-based version for now.

There are actually two schools of thought about reusing existing containers, neither of which advocate blind trust. The first says you should reuse existing work, but do a thorough audit and only use official containers - there have been numerous cases of compromised containers being made available from Docker Hub. The second says that the safest approach is to build all your containers from scratch, then you know exactly what is in them.

R.e. the built in configuration - when you look at their Dockerfiles, most containers tend to be built with a configuration that works out of the box. This doesn't stop you from mounting configuration files to change the behaviour, which is exactly what the Helm chart does. You are probably right that it is overkill to have SSL set up for the default server in the Nginx container though - I'll remove it.

**Comment by nathanlcarlson** [comment]
I'm not advocating blind trust. I'm saying that using the official image leverages the efforts of a huge community of professionals, as well as the efforts of nginx inc themselves, to create an extremely high quality image. 

The image is right here to view: https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile

**Comment by mkjpryor-stfc** [comment]
I get it. But I also need something that my infrastructure people are happy running, which is not Debian (for now). Maybe the answer is that we at CEDA run our own images that are different from the normal ESGF ones (which I *really* wanted to avoid).

Also, the official Nginx Docker image runs Nginx as root, which means it won't even run on our Kubernetes. So I would need to install an entire configuration from scratch anyway. All the Nginx image I wrote does is `yum install nginx` then install a custom config.

**Comment by philipkershaw** [comment]
@nathanlcarlson , @mkjpryor-stfc, I'm going to raise this with the XC to see there are any strong opinions either way from the collaborating centres

**Comment by mkjpryor-stfc** [comment]
@philipkershaw @nathanlcarlson 

Just to be clear, using the official Nginx image doesn't mean we don't need our own Nginx image. The decision is merely whether we use the official Nginx image as the base, or CentOS 7 + `yum install nginx`. In either case, we need to do at least the following:

  * Stop the container trying to bind privileged ports by default, even for the default server - our Kubernetes setup wouldn't even let the container start as `root` in order to bind those ports
  * Fix permissions so that the container is runnable by any user in a particular group - this is important for connecting to certain types of storage, particularly `hostPath` volumes which is what we, and I expect many other sites, will be using to serve data
  * Use a proper subprocess reaper, like `tini` - the ESGF base image I have written makes sure this is the case for all ESGF images

**Comment by mkjpryor-stfc** [comment]
Also, a decision to use the official Nginx image might result in CEDA maintaining an alternative image for the near future at least. This wouldn't be ideal.

**Comment by sashakames** [comment]
Lets raise this with the CDNOT as well, as that will reach out to tier-2 sites that may express operational issues.
