### ISSUE TITLE
custom labels on kubernetes objects

### ISSUE THREAD

**Issue by muryanto1** [ESGF/esgf-docker#129]
We need to be able to add custom labels to Kubernetes objects.
Our use case: utilize our existing ingress controller (Traefik), that selects ingress objects by label.

**Comment by mkjpryor-stfc** [comment]
@muryanto1 @jasonb5

I have added resource-specific labels. Take a look at the PR #130 for details.

Can you confirm that this satisfies your use case, then I will merge.

**Comment by muryanto1** [comment]
@mkjpryor-stfc We verified that your update to add resource-specific labels works for our use-case.  added a label for the ingress component, and verified that the label showed up in the ingress object.  Thanks!
