### ISSUE TITLE
Data directory mounting problem

### ISSUE THREAD

**Issue by HansVahlenkamp** [ESGF/esgf-docker#162]
I'm trying to install the esgf-docker future-architecture version in a Kubernetes cluster on AWS.  I configured "values.yaml" for the ESGF Helm chart to specify a data directory that is on an AWS EC2 machine from which I'm doing the installation to the AWS Kubernetes cluster. Here is the relevant section of "values.yaml":

...
data:
  enabled: true

  mounts:
    - mountPath: /data
      volumeSpec:
        hostPath:
          path: /mnt/goofys
      mountOptions:
        mountPropagation: HostToContainer

  datasets:
    - name: CMIP6
      path: CMIP6
      location: /data/CMIP6
...

After deploying the ESGF Helm chart, I logged into the running containers of the AWS Kubernetes cluster and found that their "/data" directory is empty.  It does not contain the expected data from the "/mnt/goofys" directory that is provided by the AWS EC2 machine.  Are some other options needed in "values.yaml" to get the "/data" directory mounting working properly in the containers of the AWS Kubernetes cluster?

**Comment by mkjpryor-stfc** [comment]
This is not a bug - the data directory must be mounted on the **cluster nodes**, as discussed on the esgf-docker Slack channel.
