### ISSUE TITLE
change_password.sh wrong paths

### ISSUE THREAD

**Issue by gardoll** [ESGF/esgf-docker#21]
1.
docker exec -it postgres /bin/bash -c "export ESGF_PASSWORD=${ESGF_PASSWORD} && /usr/local/bin/postgres_change_password.sh"`

postgres_change_password.sh should be renamed into change_password.sh 

2. 
docker exec -it cog /bin/bash -c "export ESGF_PASSWORD=${ESGF_PASSWORD} && /usr/local/bin/cog_change_database_password.sh"

cog_change_database_password.sh doesn't exist in the cog container : the name of the script is change_cog_database_password.sh for the tag v1.1

tag v1.1 must be reworked.

**Comment by gardoll** [comment]
[root]# docker ps -a
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                     PORTS                                                      NAMES
06ba8c45b561        esgfhub/esgf-httpd:1.1          "/usr/local/bin/do..."   42 minutes ago      Up 3 minutes (unhealthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp                   httpd
ae14d40c1667        esgfhub/esgf-idp-node:1.1       "/usr/local/tomcat..."   42 minutes ago      Up 3 minutes               8009/tcp, 0.0.0.0:8082->8080/tcp, 0.0.0.0:8445->8443/tcp   idp-node
b4242cfcf3d2        esgfhub/esgf-cog:1.1            "/usr/local/bin/do..."   42 minutes ago      Exited (1) 3 minutes ago                                                              cog
dda32a9369eb        esgfhub/esgf-data-node:1.1      "supervisord --nod..."   42 minutes ago      Up 3 minutes               0.0.0.0:8080->8080/tcp, 8009/tcp, 0.0.0.0:8443->8443/tcp   data-node
c3c542008c02        esgfhub/esgf-node-manager:1.1   "/usr/local/bin/do..."   42 minutes ago      Up 3 minutes                                                                          node-manager
68708a02c212        esgfhub/esgf-index-node:1.1     "/usr/local/tomcat..."   42 minutes ago      Up 3 minutes               8009/tcp, 0.0.0.0:8081->8080/tcp, 0.0.0.0:8444->8443/tcp   index-node
08dfbac31af7        esgfhub/esgf-solr:1.1           "/usr/local/bin/do..."   42 minutes ago      Up 3 minutes               0.0.0.0:8985->8983/tcp, 0.0.0.0:8986->8984/tcp             solr
bdd708bc912d        centos:6                        "/bin/bash"              42 minutes ago      Exited (0) 3 minutes ago                                                              esgf-config
e7cb40df4fbd        esgfhub/esgf-postgres:1.1       "supervisord --nod..."   42 minutes ago      Up 3 minutes               0.0.0.0:5432->5432/tcp                                     postgres

**Comment by LucaCinquini** [comment]
Yes this is normal. The CoG container is used to initialize the source directory tree, but after that the pages are served by the httpd container. Same with esgf_config. Maybe there's a way to improve this.

**Comment by gardoll** [comment]
The issue came from a obsolete command from the wiki:
`git checkout -b v1.1 origin/v1.1` failed (branch v1.1 doest exist) so I issued `git checkout -b v1.1` which create a new branch from master, not tag v1.1 . I fixed the wiki: it is better to checkout the tag.
