### ISSUE TITLE
Typos in esgf_dashboard.sql script

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-docker#22]
A table called esgf_dashboard.obs4mips_dmart_clients_**host**_time_geolocation is created on line 705.  
On line 718, ALTER TABLE is called on esgf_dashboard.obs4mips_dmart_variable_host_time. This causes an error. 
Stack trace:
ProgrammingError: relation "esgf_dashboard.obs4mips_dmart_clients_time_geolocation" does not exist
It appears that host should be removed from the table creation variable.

**Comment by LucaCinquini** [comment]
I am actually not sure what the correct table here is... waiting for the dashboard team to respond...

**Comment by LucaCinquini** [comment]
Fixed by dashboard team
