### ISSUE TITLE
Cannot drop language plpgsql

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-docker#23]
An error occurs when trying to drop the plpgsql language on line 902 of esgf_dashboard.sql.
Stack trace:
InternalError: cannot drop language plpgsql because extension plpgsql requires it
HINT:  You can drop extension plpgsql instead.

Changing this to 
DROP EXTENSION  IF EXISTS  plpgsql;
should fix the problem.

**Comment by LucaCinquini** [comment]
Thanks William, implemented in the Docker distribution.
