### ISSUE TITLE
Scripts using features not present in Postgres 8.4

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-docker#37]
Since we came to a consensus to use Postgres 8.4, I've been rolling back my ESGF 3.0 code to use Postgres 8.4.20.  When running the SQL scripts to import schemas, I've hit an error due to the script using a feature that's only present in Postgres 9.x

In the esgf_security.sql file, line 10 is SET lock_timeout = 0;

lock_timeout is a feature that was implemented in Postgres 9.3.  I had to remove that line to import the data in ESGF 3.0

**Comment by sashakames** [comment]
Are we avoiding the schema migrations?  That has been the standard for deploying schemas.  esgf_security is only needed on IDP nodes.  For data nodes, esgsetup followed by esginitialize should call the schema migration execution.
