### ISSUE TITLE
Support deployment to RHEL environment

### ISSUE THREAD

**Issue by fgreg** [ESGF/esgf-docker#38]
Need to provide instructions on how to deploy an ESGF docker system into a RHEL environment.

Red Hat does not support compose, swarm, or machine: https://access.redhat.com/solutions/1408853

The Red Hat supported way of running Docker on a cluster of machines is to use OpenShift: https://access.redhat.com/articles/2726491

**Comment by LucaCinquini** [comment]
It seems like Hans got the ESGF/Docker installation to work on a single host by:
o Using Docker engine from RPM
o Installing docker-compose from Docker web site
o Setting SELinux=permissive
