### ISSUE TITLE
.DS_Store in esg_config causes errors

### ISSUE THREAD

**Issue by fgreg** [ESGF/esgf-docker#63]
I tried following the instructions in https://github.com/ESGF/esgf-helm but when I got to this point

```
docker-compose run -T esgf-setup helm-values | helm upgrade esgf . --install --namespace esgf -f /Users/greguska/gitprojeects/esgf-govcloud-deploy/values.yaml -f -
```

I received a couple of errors that seemed odd:

> /opt/esgf-docker/setup-scripts/helm-values: line 41: warning: command substitution: ignored null byte in input

> Error: failed to parse -: error converting YAML to JSON: yaml: control characters are not allowed

I ran just `docker-compose run -T esgf-setup helm-values` and noticed it was trying to create a secret out of a `.DS_Store` file.

I fixed it by running `find ~/esgf_config/ -name .DS_Store -delete` and then re-running the command but maybe we should ignore all .DS_Store files? Or make it explicit so it doesn't try to process them?

https://github.com/ESGF/esgf-docker/blob/873792e6cd26615ddf356051d59110535a1a4190/setup/scripts/helm-values#L40

**Comment by mkjpryor-stfc** [comment]
@fgreg 

How did your config directory get a `.DS_Store` file in it in the first place? This is a Mac-specific thing, so I'm inclined to think that the fix here is to update the docs with a "warning" to say Mac users must run `find "$ESGF_CONFIG" -name '.DS_Store' -exec rm {} +` if they have problems.

**Comment by fgreg** [comment]
@mkjpryor-stfc Yea it's a Mac specific file. Finder automatically creates it if you open the folder in finder. It's like the `Desktop.ini` file windows automatically creates.

Maybe if we update the secret generator to give all the secrets a common extension and then only process files with that extension? Or yea like you said, just document it and move on.
