### ISSUE TITLE
Replace "realpath" from shell scripts

### ISSUE THREAD

**Issue by LucaCinquini** [ESGF/esgf-docker#87]
When generating the ESGF configuration on a Mac, the following happens:

MT-106019:esgf-docker cinquini$ ./bin/esgf-setup generate-secrets
./bin/esgf-setup: line 21: realpath: command not found
[INFO] Generating required secrets
[INFO] Created new secret 'rootadmin-password'
[INFO] Created new secret 'security-database-password'
[INFO] Created new secret 'cog-database-password'
[INFO] Created new secret 'auth-database-password'
[INFO] Created new secret 'slcs-database-password'
[INFO] Created new secret 'esgcet-database-password'
[INFO] Created new secret 'cog-secret-key'
[INFO] Created new secret 'shared-cookie-secret-key'
[INFO] Created new secret 'slcs-secret-key'
[INFO] Created new secret 'auth-secret-key'
[INFO] Done

This problem is easily solvable by installing the "realpath" executable:

https://github.com/harto/realpath-osx

but still it would be good to remove the additional dependency.

**Comment by mkjpryor-stfc** [comment]
@LucaCinquini: I'm not sure what the alternative is here, as the `docker ... -v ...` requires the full path, not a relative path.

**Comment by mkjpryor-stfc** [comment]
I've looked at this and I don't think it can be avoided. Closing as wontfix.
